apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort   # or LoadBalancer if your cluster supports it
  selector:
    app: myapp
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      nodePort: 30080    # if using NodePort (optional)
