name: Get Deployments and Services Info 33

on:
  workflow_dispatch:   # Run manually from GitHub Actions

jobs:
  get-k8s-info:
    runs-on: self-hosted
    env:
      # 👇 Make sure this path points to your kubeconfig on the runner
      KUBECONFIG: C:\Users\runner\.kube\config

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Deployments Info
        run: |
          echo === Deployments (All namespaces) ===
          kubectl get deployments -A -o wide
        shell: cmd

      - name: Get Services Info
        run: |
          echo === Services (All namespaces) ===
          kubectl get svc -A -o wide
        shell: cmd

      - name: Save Deployments and Services Info
        run: |
          kubectl get deployments -A -o wide > deployments-info.txt
          kubectl get svc -A -o wide > services-info.txt
        shell: cmd

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: k8s-deployments-services
          path: |
            deployments-info.txt
            services-info.txt
