name: Get Namespaces Info text01

on:
  push:
    branches:
      - main

jobs:
  get-namespaces-info:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Namespaces Info (Print to Logs)
        shell: cmd
        run: |
          echo Fetching all Kubernetes Namespaces...
          kubectl get namespaces
